services:
  estoualer:
    build:
      context: .
      dockerfile: Dockerfile
    image: fabiano/estoualer
    container_name: estoualer
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`estoualer.a.algumasideias.com.br`)"
      - "traefik.http.routers.gitea.entrypoints=web"
      - "traefik.http.services.gitea.loadbalancer.server.port=80"

networks:
  default:
    name: estoualer
