services:
  estoualer:
    build:
      context: .
      dockerfile: Dockerfile
    image: fabiano/estoualer
    container_name: estoualer
    restart: unless-stopped

networks:
  default:
    name: estoualer

