version: "3.9"
services:
  website:
    image: quadrinhos-website:latest
    container_name: quadrinhos-website
    build:
      context: ./website
      target: development
    working_dir: /workspace/website
    command:
      npx http-server . --port 80
    volumes:
      - .:/workspace:cached
    ports:
      - 4201:80
  api:
    image: quadrinhos-api:latest
    container_name: quadrinhos-api
    build:
      context: ./api
      target: development
    working_dir: /workspace/api
    command:
      air
    volumes:
      - .:/workspace:cached
    ports:
      - 4202:80
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
