version: "3.9"
services:
  devcontainer:
    build:
      context: .
      dockerfile: devcontainer.dockerfile
    container_name: quadrinhos-devcontainer
    working_dir: /src
    command:
      - sh
      - -c
      - |
        echo "Ready to Go!"
        while sleep 1000; do :; done
    volumes:
      - .:/src:cached
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - label:disable
  website:
    image: quadrinhos-devcontainer
    container_name: quadrinhos-website
    working_dir: /src
    command: npx serve --listen 80
    volumes:
      - ./website:/src:cached
    ports:
      - 4201:80
    security_opt:
      - seccomp:unconfined
      - label:disable
  api:
    image: quadrinhos-devcontainer
    container_name: quadrinhos-api
    working_dir: /src
    command: air
    volumes:
      - ./api:/src:cached
    ports:
      - 4202:80
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - label:disable

networks:
  default:
    name: quadrinhos-network
