version: "3.9"
services:
  website:
    image: nginx:alpine
    container_name: quadrinhos-website
    volumes:
      - ./website/nginx.conf:/etc/nginx/conf.d/default.conf:cached,z
      - ./website:/usr/share/nginx/html:cached,z
    ports:
      - 4201:80
  api:
    image: golang:1.20-buster
    container_name: quadrinhos-api
    working_dir: /workspace
    command:
      - sh
      - -c
      - |
        go install github.com/cosmtrek/air@latest
        air
    volumes:
      - ./api:/workspace:cached,z
    ports:
      - 4202:80
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
  devcontainer:
    image: golang:1.20-buster
    container_name: quadrinhos-devcontainer
    working_dir: /workspace
    command:
      - sh
      - -c
      - |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin latest
        while sleep 1000; do :; done
    volumes:
      - .:/workspace:cached,z
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
