version: "3.9"
services:
  website:
    image: nginx:alpine
    container_name: quadrinhos-website
    volumes:
      - ./website/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./website:/usr/share/nginx/html:cached
    ports:
      - 4201:80
    security_opt:
      - seccomp:unconfined
      - label:disable
  api:
    image: golang:1.21.1-bookworm
    container_name: quadrinhos-api
    working_dir: /workspace
    command:
      - sh
      - -c
      - |
        go install github.com/cosmtrek/air@latest
        air
    volumes:
      - ./api:/workspace:cached
    ports:
      - 4202:80
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - label:disable
  devcontainer:
    image: golang:1.21.1-bookworm
    container_name: quadrinhos-devcontainer
    working_dir: /workspace
    command:
      - sh
      - -c
      - |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin latest
        while sleep 1000; do :; done
    volumes:
      - .:/workspace:cached
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - label:disable
