version: "3.9"

services:
  devcontainer:
    build:
      context: .
      dockerfile: devcontainer.dockerfile
    container_name: estoualer-devcontainer
    working_dir: /src
    command:
      - sh
      - -c
      - |
        echo "Ready to Go!"
        while sleep 1000; do :; done
    volumes:
      - .:/src:cached
    ports:
      - 4201:8080
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - label:disable

networks:
  default:
    name: estoualer-network
