version: "3.9"

services:
  devcontainer:
    build:
      context: .
      dockerfile: devcontainer.dockerfile
    container_name: estoualer-devcontainer
    working_dir: /src
    command:
      - sh
      - -c
      - |
        echo "Ready to Go!"
        while sleep 1000; do :; done
    volumes:
      - .:/src:cached
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - label:disable
  website:
    build:
      context: .
      dockerfile: devcontainer.dockerfile
    container_name: estoualer-website
    working_dir: /src/website
    command: npx serve --listen 80
    volumes:
      - .:/src:cached
    ports:
      - 4201:80
    security_opt:
      - seccomp:unconfined
      - label:disable
  api:
    build:
      context: .
      dockerfile: devcontainer.dockerfile
    container_name: estoualer-api
    working_dir: /src/api
    command: air
    volumes:
      - .:/src:cached
    ports:
      - 4202:80
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - label:disable

networks:
  default:
    name: estoualer-network
