version: "3.9"
services:
  website:
    image: nginx:alpine
    container_name: quadrinhos-website
    volumes:
      - ./website/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./website:/usr/share/nginx/html:cached
    ports:
      - 4201:80
  api:
    image: golang:1.19-buster
    container_name: quadrinhos-api
    working_dir: /workspace
    command:
      sh -c "go install github.com/cosmtrek/air@latest && air"
    volumes:
      - ./api:/workspace:cached
    ports:
      - 4202:80
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
