name: Continuous deployment
on: push

jobs:
  continuous-deployment:
    name: Continuous deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - name: Build and start the container
        run: docker compose up --build --force-recreate --remove-orphans --detach

