name: Build & test

on: push

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.1
        working-directory: api

      - name: Build
        run: go build -v ./...
        working-directory: api

      - name: Test
        run: go test -v ./...
        working-directory: api
