name: Build & test

on: push

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: api/go.mod
          cache-dependency-path: api/go.sum

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: api

      - name: Build
        run: go build -buildvcs=false -v ./...
        working-directory: api

      - name: Test
        run: go test -v ./...
        working-directory: api
