name: Build & test

on: push

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: .

      - name: Build
        run: go build -buildvcs=false -v

      - name: Test
        run: go test -v
